services:
  localstack:
    image: localstack/localstack-pro:latest
    container_name: localstack-vpc-lab
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - SERVICES=ec2,sts,elbv2
      - DEFAULT_REGION=us-east-1
      - EAGER_SERVICE_LOADING=1
      - DEBUG=${DEBUG:-0}
    volumes:
      - "./volume:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 10s
      timeout: 5s
      retries: 10
